# Generated by Django 5.1.7 on 2025-03-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instance_id',
            field=models.CharField(default=52990, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='webhook_token',
            field=models.CharField(default=1234567, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
        ),
    ]
