# Generated by Django 5.1.7 on 2025-03-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_company_instance_id_company_webhook_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_token',
            field=models.CharField(default='3XPbeGYDZvDHccWEN5305lHDFogypuD3fM1ZI9yTc1cfac58', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.company'),
        ),
    ]
