# Generated by Django 5.1.8 on 2025-04-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_time_order_order_at_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
