# Generated by Django 5.1.8 on 2025-04-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_questiontemplate_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='products',
            field=models.JSONField(default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='emotions',
            field=models.JSONField(default=list, max_length=100),
        ),
    ]
