# Generated by Django 5.1.8 on 2025-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_analytics_products_alter_analytics_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
