# Generated by Django 5.1.8 on 2025-04-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_order_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontemplate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.order'),
        ),
    ]
