# Generated by Django 5.2 on 2025-05-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_questiontemplate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontemplate',
            name='question',
            field=models.TextField(),
        ),
    ]
