# Generated by Django 5.2 on 2025-05-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_questiontemplate_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='sentiment_score',
        ),
    ]
